/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavLayoutImport } from './routes/_NavLayout'
import { Route as HomeLayoutImport } from './routes/_HomeLayout'
import { Route as IndexImport } from './routes/index'
import { Route as TablesIndexImport } from './routes/tables/index'
import { Route as HomeLayoutForgotPasswordIndexImport } from './routes/_HomeLayout.forgot-password/index'
import { Route as NavLayoutUserWorkspaceImport } from './routes/_NavLayout.user/workspace'
import { Route as NavLayoutUserProfileImport } from './routes/_NavLayout.user/profile'
import { Route as NavLayoutUserHandledCasesImport } from './routes/_NavLayout.user/handled-cases'
import { Route as NavLayoutUserDashboardImport } from './routes/_NavLayout.user/dashboard'
import { Route as NavLayoutUserAnalysisImport } from './routes/_NavLayout.user/analysis'
import { Route as NavLayoutAdminDashboardImport } from './routes/_NavLayout.admin/dashboard'
import { Route as NavLayoutAdminWorkspaceIndexImport } from './routes/_NavLayout.admin/workspace/index'
import { Route as NavLayoutAdminUsersIndexImport } from './routes/_NavLayout.admin/users/index'
import { Route as NavLayoutAdminTablesIndexImport } from './routes/_NavLayout.admin/tables/index'
import { Route as NavLayoutAdminProfileIndexImport } from './routes/_NavLayout.admin/profile/index'
import { Route as NavLayoutAdminAnalysisIndexImport } from './routes/_NavLayout.admin/analysis/index'

// Create/Update Routes

const NavLayoutRoute = NavLayoutImport.update({
  id: '/_NavLayout',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_HomeLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TablesIndexRoute = TablesIndexImport.update({
  path: '/tables/',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutForgotPasswordIndexRoute =
  HomeLayoutForgotPasswordIndexImport.update({
    path: '/forgot-password/',
    getParentRoute: () => HomeLayoutRoute,
  } as any)

const NavLayoutUserWorkspaceRoute = NavLayoutUserWorkspaceImport.update({
  path: '/user/workspace',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutUserProfileRoute = NavLayoutUserProfileImport.update({
  path: '/user/profile',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutUserHandledCasesRoute = NavLayoutUserHandledCasesImport.update({
  path: '/user/handled-cases',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutUserDashboardRoute = NavLayoutUserDashboardImport.update({
  path: '/user/dashboard',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutUserAnalysisRoute = NavLayoutUserAnalysisImport.update({
  path: '/user/analysis',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutAdminDashboardRoute = NavLayoutAdminDashboardImport.update({
  path: '/admin/dashboard',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutAdminWorkspaceIndexRoute =
  NavLayoutAdminWorkspaceIndexImport.update({
    path: '/admin/workspace/',
    getParentRoute: () => NavLayoutRoute,
  } as any)

const NavLayoutAdminUsersIndexRoute = NavLayoutAdminUsersIndexImport.update({
  path: '/admin/users/',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutAdminTablesIndexRoute = NavLayoutAdminTablesIndexImport.update({
  path: '/admin/tables/',
  getParentRoute: () => NavLayoutRoute,
} as any)

const NavLayoutAdminProfileIndexRoute = NavLayoutAdminProfileIndexImport.update(
  {
    path: '/admin/profile/',
    getParentRoute: () => NavLayoutRoute,
  } as any,
)

const NavLayoutAdminAnalysisIndexRoute =
  NavLayoutAdminAnalysisIndexImport.update({
    path: '/admin/analysis/',
    getParentRoute: () => NavLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_HomeLayout': {
      id: '/_HomeLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_NavLayout': {
      id: '/_NavLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavLayoutImport
      parentRoute: typeof rootRoute
    }
    '/tables/': {
      id: '/tables/'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesIndexImport
      parentRoute: typeof rootRoute
    }
    '/_NavLayout/admin/dashboard': {
      id: '/_NavLayout/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof NavLayoutAdminDashboardImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/user/analysis': {
      id: '/_NavLayout/user/analysis'
      path: '/user/analysis'
      fullPath: '/user/analysis'
      preLoaderRoute: typeof NavLayoutUserAnalysisImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/user/dashboard': {
      id: '/_NavLayout/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof NavLayoutUserDashboardImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/user/handled-cases': {
      id: '/_NavLayout/user/handled-cases'
      path: '/user/handled-cases'
      fullPath: '/user/handled-cases'
      preLoaderRoute: typeof NavLayoutUserHandledCasesImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/user/profile': {
      id: '/_NavLayout/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof NavLayoutUserProfileImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/user/workspace': {
      id: '/_NavLayout/user/workspace'
      path: '/user/workspace'
      fullPath: '/user/workspace'
      preLoaderRoute: typeof NavLayoutUserWorkspaceImport
      parentRoute: typeof NavLayoutImport
    }
    '/_HomeLayout/forgot-password/': {
      id: '/_HomeLayout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof HomeLayoutForgotPasswordIndexImport
      parentRoute: typeof HomeLayoutImport
    }
    '/_NavLayout/admin/analysis/': {
      id: '/_NavLayout/admin/analysis/'
      path: '/admin/analysis'
      fullPath: '/admin/analysis'
      preLoaderRoute: typeof NavLayoutAdminAnalysisIndexImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/admin/profile/': {
      id: '/_NavLayout/admin/profile/'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof NavLayoutAdminProfileIndexImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/admin/tables/': {
      id: '/_NavLayout/admin/tables/'
      path: '/admin/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof NavLayoutAdminTablesIndexImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/admin/users/': {
      id: '/_NavLayout/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof NavLayoutAdminUsersIndexImport
      parentRoute: typeof NavLayoutImport
    }
    '/_NavLayout/admin/workspace/': {
      id: '/_NavLayout/admin/workspace/'
      path: '/admin/workspace'
      fullPath: '/admin/workspace'
      preLoaderRoute: typeof NavLayoutAdminWorkspaceIndexImport
      parentRoute: typeof NavLayoutImport
    }
  }
}

// Create and export the route tree

interface HomeLayoutRouteChildren {
  HomeLayoutForgotPasswordIndexRoute: typeof HomeLayoutForgotPasswordIndexRoute
}

const HomeLayoutRouteChildren: HomeLayoutRouteChildren = {
  HomeLayoutForgotPasswordIndexRoute: HomeLayoutForgotPasswordIndexRoute,
}

const HomeLayoutRouteWithChildren = HomeLayoutRoute._addFileChildren(
  HomeLayoutRouteChildren,
)

interface NavLayoutRouteChildren {
  NavLayoutAdminDashboardRoute: typeof NavLayoutAdminDashboardRoute
  NavLayoutUserAnalysisRoute: typeof NavLayoutUserAnalysisRoute
  NavLayoutUserDashboardRoute: typeof NavLayoutUserDashboardRoute
  NavLayoutUserHandledCasesRoute: typeof NavLayoutUserHandledCasesRoute
  NavLayoutUserProfileRoute: typeof NavLayoutUserProfileRoute
  NavLayoutUserWorkspaceRoute: typeof NavLayoutUserWorkspaceRoute
  NavLayoutAdminAnalysisIndexRoute: typeof NavLayoutAdminAnalysisIndexRoute
  NavLayoutAdminProfileIndexRoute: typeof NavLayoutAdminProfileIndexRoute
  NavLayoutAdminTablesIndexRoute: typeof NavLayoutAdminTablesIndexRoute
  NavLayoutAdminUsersIndexRoute: typeof NavLayoutAdminUsersIndexRoute
  NavLayoutAdminWorkspaceIndexRoute: typeof NavLayoutAdminWorkspaceIndexRoute
}

const NavLayoutRouteChildren: NavLayoutRouteChildren = {
  NavLayoutAdminDashboardRoute: NavLayoutAdminDashboardRoute,
  NavLayoutUserAnalysisRoute: NavLayoutUserAnalysisRoute,
  NavLayoutUserDashboardRoute: NavLayoutUserDashboardRoute,
  NavLayoutUserHandledCasesRoute: NavLayoutUserHandledCasesRoute,
  NavLayoutUserProfileRoute: NavLayoutUserProfileRoute,
  NavLayoutUserWorkspaceRoute: NavLayoutUserWorkspaceRoute,
  NavLayoutAdminAnalysisIndexRoute: NavLayoutAdminAnalysisIndexRoute,
  NavLayoutAdminProfileIndexRoute: NavLayoutAdminProfileIndexRoute,
  NavLayoutAdminTablesIndexRoute: NavLayoutAdminTablesIndexRoute,
  NavLayoutAdminUsersIndexRoute: NavLayoutAdminUsersIndexRoute,
  NavLayoutAdminWorkspaceIndexRoute: NavLayoutAdminWorkspaceIndexRoute,
}

const NavLayoutRouteWithChildren = NavLayoutRoute._addFileChildren(
  NavLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof NavLayoutRouteWithChildren
  '/tables': typeof TablesIndexRoute
  '/admin/dashboard': typeof NavLayoutAdminDashboardRoute
  '/user/analysis': typeof NavLayoutUserAnalysisRoute
  '/user/dashboard': typeof NavLayoutUserDashboardRoute
  '/user/handled-cases': typeof NavLayoutUserHandledCasesRoute
  '/user/profile': typeof NavLayoutUserProfileRoute
  '/user/workspace': typeof NavLayoutUserWorkspaceRoute
  '/forgot-password': typeof HomeLayoutForgotPasswordIndexRoute
  '/admin/analysis': typeof NavLayoutAdminAnalysisIndexRoute
  '/admin/profile': typeof NavLayoutAdminProfileIndexRoute
  '/admin/tables': typeof NavLayoutAdminTablesIndexRoute
  '/admin/users': typeof NavLayoutAdminUsersIndexRoute
  '/admin/workspace': typeof NavLayoutAdminWorkspaceIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof NavLayoutRouteWithChildren
  '/tables': typeof TablesIndexRoute
  '/admin/dashboard': typeof NavLayoutAdminDashboardRoute
  '/user/analysis': typeof NavLayoutUserAnalysisRoute
  '/user/dashboard': typeof NavLayoutUserDashboardRoute
  '/user/handled-cases': typeof NavLayoutUserHandledCasesRoute
  '/user/profile': typeof NavLayoutUserProfileRoute
  '/user/workspace': typeof NavLayoutUserWorkspaceRoute
  '/forgot-password': typeof HomeLayoutForgotPasswordIndexRoute
  '/admin/analysis': typeof NavLayoutAdminAnalysisIndexRoute
  '/admin/profile': typeof NavLayoutAdminProfileIndexRoute
  '/admin/tables': typeof NavLayoutAdminTablesIndexRoute
  '/admin/users': typeof NavLayoutAdminUsersIndexRoute
  '/admin/workspace': typeof NavLayoutAdminWorkspaceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_HomeLayout': typeof HomeLayoutRouteWithChildren
  '/_NavLayout': typeof NavLayoutRouteWithChildren
  '/tables/': typeof TablesIndexRoute
  '/_NavLayout/admin/dashboard': typeof NavLayoutAdminDashboardRoute
  '/_NavLayout/user/analysis': typeof NavLayoutUserAnalysisRoute
  '/_NavLayout/user/dashboard': typeof NavLayoutUserDashboardRoute
  '/_NavLayout/user/handled-cases': typeof NavLayoutUserHandledCasesRoute
  '/_NavLayout/user/profile': typeof NavLayoutUserProfileRoute
  '/_NavLayout/user/workspace': typeof NavLayoutUserWorkspaceRoute
  '/_HomeLayout/forgot-password/': typeof HomeLayoutForgotPasswordIndexRoute
  '/_NavLayout/admin/analysis/': typeof NavLayoutAdminAnalysisIndexRoute
  '/_NavLayout/admin/profile/': typeof NavLayoutAdminProfileIndexRoute
  '/_NavLayout/admin/tables/': typeof NavLayoutAdminTablesIndexRoute
  '/_NavLayout/admin/users/': typeof NavLayoutAdminUsersIndexRoute
  '/_NavLayout/admin/workspace/': typeof NavLayoutAdminWorkspaceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/tables'
    | '/admin/dashboard'
    | '/user/analysis'
    | '/user/dashboard'
    | '/user/handled-cases'
    | '/user/profile'
    | '/user/workspace'
    | '/forgot-password'
    | '/admin/analysis'
    | '/admin/profile'
    | '/admin/tables'
    | '/admin/users'
    | '/admin/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/tables'
    | '/admin/dashboard'
    | '/user/analysis'
    | '/user/dashboard'
    | '/user/handled-cases'
    | '/user/profile'
    | '/user/workspace'
    | '/forgot-password'
    | '/admin/analysis'
    | '/admin/profile'
    | '/admin/tables'
    | '/admin/users'
    | '/admin/workspace'
  id:
    | '__root__'
    | '/'
    | '/_HomeLayout'
    | '/_NavLayout'
    | '/tables/'
    | '/_NavLayout/admin/dashboard'
    | '/_NavLayout/user/analysis'
    | '/_NavLayout/user/dashboard'
    | '/_NavLayout/user/handled-cases'
    | '/_NavLayout/user/profile'
    | '/_NavLayout/user/workspace'
    | '/_HomeLayout/forgot-password/'
    | '/_NavLayout/admin/analysis/'
    | '/_NavLayout/admin/profile/'
    | '/_NavLayout/admin/tables/'
    | '/_NavLayout/admin/users/'
    | '/_NavLayout/admin/workspace/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeLayoutRoute: typeof HomeLayoutRouteWithChildren
  NavLayoutRoute: typeof NavLayoutRouteWithChildren
  TablesIndexRoute: typeof TablesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeLayoutRoute: HomeLayoutRouteWithChildren,
  NavLayoutRoute: NavLayoutRouteWithChildren,
  TablesIndexRoute: TablesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_HomeLayout",
        "/_NavLayout",
        "/tables/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_HomeLayout": {
      "filePath": "_HomeLayout.jsx",
      "children": [
        "/_HomeLayout/forgot-password/"
      ]
    },
    "/_NavLayout": {
      "filePath": "_NavLayout.jsx",
      "children": [
        "/_NavLayout/admin/dashboard",
        "/_NavLayout/user/analysis",
        "/_NavLayout/user/dashboard",
        "/_NavLayout/user/handled-cases",
        "/_NavLayout/user/profile",
        "/_NavLayout/user/workspace",
        "/_NavLayout/admin/analysis/",
        "/_NavLayout/admin/profile/",
        "/_NavLayout/admin/tables/",
        "/_NavLayout/admin/users/",
        "/_NavLayout/admin/workspace/"
      ]
    },
    "/tables/": {
      "filePath": "tables/index.jsx"
    },
    "/_NavLayout/admin/dashboard": {
      "filePath": "_NavLayout.admin/dashboard.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/user/analysis": {
      "filePath": "_NavLayout.user/analysis.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/user/dashboard": {
      "filePath": "_NavLayout.user/dashboard.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/user/handled-cases": {
      "filePath": "_NavLayout.user/handled-cases.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/user/profile": {
      "filePath": "_NavLayout.user/profile.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/user/workspace": {
      "filePath": "_NavLayout.user/workspace.jsx",
      "parent": "/_NavLayout"
    },
    "/_HomeLayout/forgot-password/": {
      "filePath": "_HomeLayout.forgot-password/index.jsx",
      "parent": "/_HomeLayout"
    },
    "/_NavLayout/admin/analysis/": {
      "filePath": "_NavLayout.admin/analysis/index.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/admin/profile/": {
      "filePath": "_NavLayout.admin/profile/index.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/admin/tables/": {
      "filePath": "_NavLayout.admin/tables/index.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/admin/users/": {
      "filePath": "_NavLayout.admin/users/index.jsx",
      "parent": "/_NavLayout"
    },
    "/_NavLayout/admin/workspace/": {
      "filePath": "_NavLayout.admin/workspace/index.jsx",
      "parent": "/_NavLayout"
    }
  }
}
ROUTE_MANIFEST_END */
